### PR TITLE
Add workflow

### LINKED ISSUE #3: Document workflow & actions

### PR DESCRIPTION
**Pull request by floo51**
Handles #3 

Add_workflow_by_floo51_·_Pull_Request__12_·_CaenCamp_usine-distribuee

### CODE REVIEW

**Review by Kmaschta — COMMENTED** [review]
Do we need a `MANAGEMENT_REJECTED` or/and `MANAGEMENT_ABORTED` ?

**Comment by alexisjanvier** [comment]
@floo51 Damn, we don't have the same status :(

```
table.enu(
  'status',
  ['to_dispatch', 'rejected', 'to_confirm', 'assigned', 'in_production', 'produced', 'delivered'],
  { useNative: true, enumName: 'request_status_type' }
```

**Comment by floo51** [comment]
I always try to prefix statuses with the main role interested in the status. Because all statuses don't make sense for all roles.

**Review by alexisjanvier — COMMENTED** [review]
Status in migration (not merged !) : 'to_dispatch', 'rejected', 'to_confirm', 'assigned', 'in_production', 'produced', 'delivered'

**Comment by tberriot** [comment]
@floo51 we just added "In production" because it seems to make sense. We dont't validate it with @tmaziere

**Review by alexisjanvier — APPROVED** [review]

**Review by alexisjanvier — APPROVED** [review]

**Pull request merged**
