### PR TITLE
Add missing fields on request entity

### LINKED ISSUE #23: Missing fields on request entity
Three fields [need to be added](https://docs.google.com/document/d/1TN9xHEDVXySSdt1AAX0wxRYDw5d9lPtJCBuZpYKKibk/edit#heading=h.e9igj1dpbz0e) to `request` entity :

- requester_other_type : if _Other_ selected on `request_type`, requester need to give precision
- forecast_number_of_mask : in `Prevision` step on form
- forecast_number_of_days : in `Prevision` step on form

### PR DESCRIPTION
**Pull request by tberriot**

### CODE REVIEW

**Review by Kmaschta — COMMENTED** [review]
Sorry, I implemented them in #25 ! It's already merged

**Comment by tberriot** [comment]
It miss one more (request_other_type)
I'm gonna change my PR

**Review by Kmaschta — CHANGES_REQUESTED** [review]
Can you add a new migration instead of updating one?
This will break local environments if you don't

**Comment by tberriot** [comment]
ok, sorry

**Review by Kmaschta — APPROVED** [review]

**Review by alexisjanvier — APPROVED** [review]

**Pull request merged**
